# Generated by Django 4.2.7 on 2025-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='roles',
            field=models.ManyToManyField(default='HBSTemsilci', to='api.agentrole', verbose_name='Roller'),
        ),
    ]
