# Generated by Django 4.2.7 on 2025-07-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agent_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dersatamasi',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eskepevent',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hatanotu',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitaptahlili',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peerid',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quranpage',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
