# Generated by Django 4.2.7 on 2025-08-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_savedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorvideolink',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='api.teacher'),
        ),
    ]
