# Generated by Django 4.2.7 on 2025-09-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_aboutcard_aboutgalleryimage_aboutpage_aboutstat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcard',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Kart', 'verbose_name_plural': 'Kartlar'},
        ),
        migrations.AlterModelOptions(
            name='aboutgalleryimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Galeri görseli', 'verbose_name_plural': 'Galeri görselleri'},
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Hakkımızda Sayfası', 'verbose_name_plural': 'Hakkımızda Sayfaları'},
        ),
        migrations.AlterModelOptions(
            name='aboutstat',
            options={'ordering': ['order', 'id'], 'verbose_name': 'İstatistik', 'verbose_name_plural': 'İstatistikler'},
        ),
        migrations.AlterModelOptions(
            name='abouttype',
            options={'verbose_name': 'Hakkımızda Türü', 'verbose_name_plural': 'Hakkımızda Türleri'},
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.aboutpage', verbose_name='Sayfa'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='pills',
            field=models.JSONField(blank=True, default=list, help_text='Küçük etiketler (liste). Örn: ["Mentorluk","Ölçme"]', verbose_name='Etiketler'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='text',
            field=models.TextField(blank=True, verbose_name='Metin'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='aboutgalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=160, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='aboutgalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/gallery/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='aboutgalleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='aboutgalleryimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.aboutpage', verbose_name='Sayfa'),
        ),
        migrations.AlterField(
            model_name='aboutgalleryimage',
            name='url',
            field=models.URLField(blank=True, help_text='Yerel dosya yerine link kullanacaksanız doldurun.', null=True, verbose_name='Harici görsel URL’si'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/hero/', verbose_name='Hero görseli'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Yayınlansın mı?'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.abouttype', verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='label',
            field=models.CharField(max_length=80, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.aboutpage', verbose_name='Sayfa'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='value',
            field=models.CharField(max_length=40, verbose_name='Değer'),
        ),
        migrations.AlterField(
            model_name='abouttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='abouttype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Kısa ad (slug)'),
        ),
    ]
