# Generated by Django 4.2.7 on 2024-08-10 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Talep Seçenek',
                'verbose_name_plural': 'Talep Seçenekleri',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_coupon', models.BooleanField(default=False)),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Talep İstek Seçenek',
                'verbose_name_plural': 'Talep İstek Seçenekleri',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, default='category.jpg', null=True, upload_to='course-file')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax_rate', models.IntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ülke',
                'verbose_name_plural': 'Ülkeler',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('image', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Turkce', 'Türkçe'), ('Ingilizce', 'İngilizce'), ('Arapca', 'Arapça')], default='Turkce', max_length=100)),
                ('level', models.CharField(choices=[('Başlangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100)),
                ('platform_status', models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayinlanmis', max_length=100)),
                ('teacher_course_status', models.CharField(choices=[('Taslak', 'Taslak'), ('Pasif', 'Pasif'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayinlanmis', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('course_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Meslek',
                'verbose_name_plural': 'Meslekler',
            },
        ),
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soru Cevap',
                'verbose_name_plural': 'Soru Cevaplar',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('variant_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
            options={
                'verbose_name': 'Müfredat',
                'verbose_name_plural': 'Müfredatlar',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İstek',
                'verbose_name_plural': 'İstekler',
            },
        ),
        migrations.CreateModel(
            name='VariantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('content_duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview', models.BooleanField(default=False)),
                ('variant_item_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_items', to='api.variant')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='course-file')),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eğitmen',
                'verbose_name_plural': 'Eğitmenler',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Yıldız'), (2, '2 Yıldız'), (3, '3 Yıldız'), (4, '4 Yıldız'), (5, '5 Yıldız')], default=None)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
            },
        ),
        migrations.CreateModel(
            name='Question_Answer_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('qam_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question_answer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soru Cevap Mesaj',
                'verbose_name_plural': 'Soru Cevap Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New Order', 'New Order'), ('New Review', 'New Review'), ('New Course Question', 'New Course Question'), ('Draft', 'Draft'), ('Course Published', 'Course Published'), ('Course Enrollment Completed', 'Course Enrollment Completed')], max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cartorder')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cartorderitem')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.review')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.TextField()),
                ('note_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
            },
        ),
        migrations.CreateModel(
            name='Hafizbilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(default='', max_length=150)),
                ('babaadi', models.CharField(default='', max_length=150)),
                ('tcno', models.CharField(default='', max_length=150)),
                ('adres', models.CharField(default='', max_length=150)),
                ('adresIl', models.CharField(default='', max_length=150)),
                ('adresIlce', models.CharField(default='', max_length=150)),
                ('hafizlikbitirmeyili', models.CharField(choices=[('1946', '1946'), ('1971', '1971'), ('2011', '2011'), ('1940', '1940'), ('1961', '1961'), ('1995', '1995'), ('1931', '1931'), ('2017', '2017'), ('1972', '1972'), ('2022', '2022'), ('1935', '1935'), ('1951', '1951'), ('1954', '1954'), ('1936', '1936'), ('1947', '1947'), ('2007', '2007'), ('1981', '1981'), ('2005', '2005'), ('1986', '1986'), ('1999', '1999'), ('2009', '2009'), ('1937', '1937'), ('2023', '2023'), ('2018', '2018'), ('1994', '1994'), ('1939', '1939'), ('1974', '1974'), ('1997', '1997'), ('1969', '1969'), ('1959', '1959'), ('1968', '1968'), ('1962', '1962'), ('1996', '1996'), ('2006', '2006'), ('2010', '2010'), ('1960', '1960'), ('1964', '1964'), ('2012', '2012'), ('1956', '1956'), ('1970', '1970'), ('1977', '1977'), ('2015', '2015'), ('1955', '1955'), ('1976', '1976'), ('1975', '1975'), ('1949', '1949'), ('1957', '1957'), ('1943', '1943'), ('2013', '2013'), ('2021', '2021'), ('2020', '2020'), ('1967', '1967'), ('2003', '2003'), ('1941', '1941'), ('1992', '1992'), ('2016', '2016'), ('2004', '2004'), ('1990', '1990'), ('2002', '2002'), ('1952', '1952'), ('1993', '1993'), ('1953', '1953'), ('1966', '1966'), ('1983', '1983'), ('1950', '1950'), ('1932', '1932'), ('1980', '1980'), ('1965', '1965'), ('1934', '1934'), ('2000', '2000'), ('1973', '1973'), ('1987', '1987'), ('1948', '1948'), ('1988', '1988'), ('1985', '1985'), ('1958', '1958'), ('2014', '2014'), ('2008', '2008'), ('2019', '2019'), ('1991', '1991'), ('1933', '1933'), ('2001', '2001'), ('1963', '1963'), ('1978', '1978'), ('1930', '1930'), ('1938', '1938'), ('1979', '1979'), ('1942', '1942'), ('1982', '1982'), ('1998', '1998'), ('1984', '1984'), ('1945', '1945'), ('1944', '1944'), ('1989', '1989')], default='', max_length=8)),
                ('evtel', models.CharField(default='', max_length=150)),
                ('istel', models.CharField(default='', max_length=150)),
                ('ceptel', models.CharField(default='', max_length=150)),
                ('isMarried', models.CharField(choices=[('evli', 'Evli'), ('bekar', 'Bekar')], default='', max_length=150)),
                ('ePosta', models.CharField(default='', max_length=150)),
                ('hafizlikyaptigikursadi', models.CharField(default='', max_length=150)),
                ('hafizlikyaptigikursili', models.CharField(default='', max_length=150)),
                ('gorev', models.CharField(default='', max_length=150)),
                ('hafizlikhocaadi', models.CharField(default='', max_length=150)),
                ('hafizlikhocasoyadi', models.CharField(default='', max_length=150)),
                ('hafizlikhocaceptel', models.CharField(default='', max_length=150)),
                ('hafizlikarkadasadi', models.CharField(default='', max_length=150)),
                ('hafizlikarkadasoyad', models.CharField(default='', max_length=150)),
                ('hafizlikarkadasceptel', models.CharField(default='', max_length=150)),
                ('referanstcno', models.CharField(default='', max_length=150)),
                ('onaydurumu', models.CharField(choices=[('onaylandi', 'Onaylandi'), ('onaylanmadi', 'Onaylanmadi')], default='', max_length=150)),
                ('decription', models.TextField(blank=True)),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'ios'), ('windows', 'Windows')], max_length=8)),
                ('gender', models.CharField(choices=[('erkek', 'Erkek'), ('kadin', 'Kadın')], default='', max_length=50)),
                ('yas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Meslekler', to='api.job')),
            ],
            options={
                'verbose_name': 'Hafız Bilgi',
                'verbose_name_plural': 'Hafız Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartorderitem')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kaydedilan Kurs',
                'verbose_name_plural': 'Kaydedilen Kurslar',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher')),
                ('used_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödül',
                'verbose_name_plural': 'Ödüller',
            },
        ),
        migrations.CreateModel(
            name='CompletedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variantitem')),
            ],
            options={
                'verbose_name': 'Tamamlanmış Ders',
                'verbose_name_plural': 'Tamamlanmış Dersler',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
            },
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.coupon'),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='api.course'),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='api.cartorder'),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.coupon'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='api.teacher'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('cart_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talep',
                'verbose_name_plural': 'Talepler',
            },
        ),
    ]
