# Generated by Django 4.2.7 on 2024-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='onaydurumu',
            field=models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaylanmadı', 'Onaylanmadı')], default='', max_length=150),
        ),
    ]
