# Generated by Django 4.2.7 on 2024-08-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hafizbilgileri',
            name='decription',
        ),
        migrations.AddField(
            model_name='hafizbilgileri',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agent'),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='babaadi',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='evtel',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='gorev',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='hafizlikarkadasadi',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='hafizlikarkadasceptel',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='hafizlikarkadasoyad',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='hafizlikhocaadi',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='hafizlikhocaceptel',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='hafizlikhocasoyadi',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='isMarried',
            field=models.CharField(blank=True, choices=[('evli', 'Evli'), ('bekar', 'Bekar')], default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='istel',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='referanstcno',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='tcno',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='yas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
