# Generated by Django 4.2.7 on 2025-05-28 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersatamasi',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
