# Generated by Django 4.2.7 on 2024-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Eğitmen', 'verbose_name_plural': 'Eğitmenler'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='initial_total',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tax_fee',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='initial_total',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='tax_fee',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='total',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Türkçe', 'Türkçe'), ('İngilizce', 'İngilizce'), ('Arapça', 'Arapça')], default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Başlangıç', 'Başlangıç'), ('Orta', 'Orta'), ('İleri Seviye', 'İleri Seviye')], default='Beginner', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_course_status',
            field=models.CharField(choices=[('Taslak', 'Taslak'), ('Pasif', 'Pasif'), ('Yayınlanmış', 'Yayınlanmış')], default='Published', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Yıldız'), (2, '2 Yıldız'), (3, '3 Yıldız'), (4, '4 Yıldız'), (5, '5 Yıldız')], default=None),
        ),
    ]
