# Generated by Django 4.2.7 on 2024-08-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_hafizbilgileri_decription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country'),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.job'),
        ),
    ]
