# Generated by Django 4.2.7 on 2024-08-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hafizbilgileri_onaydurumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='gender',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='', max_length=50),
        ),
    ]
