# Generated by Django 4.2.7 on 2024-07-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Talep', 'verbose_name_plural': 'Talepler'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name': 'TalepSeçenek', 'verbose_name_plural': 'TalepSeçenekleri'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitem',
            options={'verbose_name': 'Talep İstek Seçenek', 'verbose_name_plural': 'Talep İstek Seçenekleri'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifika', 'verbose_name_plural': 'Sertifikalar'},
        ),
        migrations.AlterModelOptions(
            name='completedlesson',
            options={'verbose_name': 'TamamlanmışDers', 'verbose_name_plural': 'TamamlanmışDersler'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Ülke', 'verbose_name_plural': 'Ülkeler'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Ödül', 'verbose_name_plural': 'Ödüller'},
        ),
        migrations.AlterModelOptions(
            name='enrolledcourse',
            options={'verbose_name': 'KaydedilanKurs', 'verbose_name_plural': 'KaydedilenKurslar'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Not', 'verbose_name_plural': 'Notlar'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Bildirim', 'verbose_name_plural': 'Bildirimler'},
        ),
        migrations.AlterModelOptions(
            name='question_answer',
            options={'verbose_name': 'SoruCevap', 'verbose_name_plural': 'SoruCevaplar'},
        ),
        migrations.AlterModelOptions(
            name='question_answer_message',
            options={'verbose_name': 'SoruCevapMesaj', 'verbose_name_plural': 'SoruCevapMesajlar'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Müfredat', 'verbose_name_plural': 'Müfredatlar'},
        ),
        migrations.AlterModelOptions(
            name='variantitem',
            options={'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'İstek', 'verbose_name_plural': 'İstekler'},
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Turkce', 'Türkçe'), ('Ingilizce', 'İngilizce'), ('Arapca', 'Arapça')], default='Türkçe', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Başlangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Başlangıç', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='platform_status',
            field=models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayınlanmış', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_course_status',
            field=models.CharField(choices=[('Taslak', 'Taslak'), ('Pasif', 'Pasif'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayınlanmış', max_length=100),
        ),
    ]
