# Generated by Django 4.2.7 on 2025-05-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dersatamasi_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='email',
        ),
        migrations.RemoveField(
            model_name='stajer',
            name='email',
        ),
    ]
