# Generated by Django 4.2.7 on 2025-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ogrenci_email_remove_stajer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoordinatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ogrenci', 'Ogrenci'), ('Stajer', 'Stajer'), ('Genel', 'Genel'), ('AkademiKoordinator', 'AkademiKoordinator'), ('HBSKoordinator', 'HBSKoordinator'), ('HDMKoordinator', 'HDMKoordinator')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='koordinator',
            name='role',
        ),
        migrations.AddField(
            model_name='koordinator',
            name='roles',
            field=models.ManyToManyField(to='api.koordinatorrole', verbose_name='Roller'),
        ),
    ]
