# Generated by Django 4.2.7 on 2024-08-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hafizbilgileri_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='adresIl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AdresIl', to='api.city'),
        ),
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='hafizlikyaptigikursili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='KursIlı', to='api.city'),
        ),
    ]
