# Generated by Django 4.2.7 on 2025-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ders_active_dersatamasi_active_eskepevent_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='derssonuraporu',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eskepproje',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantderssonuraporu',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantderssonuraporuitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantkitaptahlili',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantkitaptahliliitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantodevitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
