# Generated by Django 4.2.7 on 2024-08-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hafizbilgileri_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Üye Görevi',
                'verbose_name_plural': 'Üye Görevleri',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=150)),
                ('ImageUrl', models.FileField(blank=True, default='default.jpg', null=True, upload_to='course-file')),
                ('IsExpand', models.BooleanField()),
                ('RatingColor', models.CharField(max_length=25)),
                ('ReportingPerson', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Organizasyon Üyesi',
                'verbose_name_plural': 'Organizasyon Üyeleri',
            },
        ),
    ]
