# Generated by Django 4.2.7 on 2025-06-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_koordinatorrole_remove_koordinator_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AkademiTeacher', 'AkademiTeacher'), ('ESKEPTeacher', 'ESKEPTeacher'), ('HBSTeacher', 'HBSTeacher'), ('HDMTeacher', 'HDMTeacher')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='roles',
            field=models.ManyToManyField(to='api.teacherrole', verbose_name='Roller'),
        ),
    ]
