# Generated by Django 4.2.7 on 2024-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_level_alter_course_platform_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Turkce', 'Türkçe'), ('Ingilizce', 'İngilizce'), ('Arapca', 'Arapça')], default='Turkce', max_length=100),
        ),
    ]
