# Generated by Django 4.2.7 on 2025-07-31 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_derssonuraporu_active_eskepproje_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_answer_messagederssonuraporu',
            name='koordinator',
        ),
        migrations.RemoveField(
            model_name='question_answer_messagederssonuraporu',
            name='ogrenciStajer',
        ),
        migrations.RemoveField(
            model_name='question_answer_messageeskepproje',
            name='koordinator',
        ),
        migrations.RemoveField(
            model_name='question_answer_messageeskepproje',
            name='ogrenciStajer',
        ),
        migrations.RemoveField(
            model_name='question_answer_messagekitaptahlili',
            name='koordinator',
        ),
        migrations.RemoveField(
            model_name='question_answer_messagekitaptahlili',
            name='ogrenciStajer',
        ),
        migrations.RemoveField(
            model_name='question_answerderssonuraporu',
            name='koordinator',
        ),
        migrations.RemoveField(
            model_name='question_answerderssonuraporu',
            name='ogrenciStajer',
        ),
        migrations.RemoveField(
            model_name='question_answereskepproje',
            name='koordinator',
        ),
        migrations.RemoveField(
            model_name='question_answereskepproje',
            name='ogrenciStajer',
        ),
        migrations.RemoveField(
            model_name='question_answerkitaptahlili',
            name='koordinator',
        ),
        migrations.RemoveField(
            model_name='question_answerkitaptahlili',
            name='ogrenciStajer',
        ),
        migrations.AddField(
            model_name='question_answer_messagederssonuraporu',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan_mesaj_derssonuraporu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answer_messagederssonuraporu',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen_mesaj_derssonuraporu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answer_messageeskepproje',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan_mesaj_proje', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answer_messageeskepproje',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen_mesaj_proje', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answer_messagekitaptahlili',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan_mesaj_kitap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answer_messagekitaptahlili',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen_mesaj_kitap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answerderssonuraporu',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan_derssonuraporu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answerderssonuraporu',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen_derssonuraporu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answereskepproje',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan_proje', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answereskepproje',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen_proje', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answerkitaptahlili',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan_kitap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answerkitaptahlili',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen_kitap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_answer_messagekitaptahlili',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question_answerderssonuraporu'),
        ),
        migrations.AlterField(
            model_name='question_answer_messageodev',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan_mesaj_odev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_answer_messageodev',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen_mesaj_odev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_answerodev',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan_odev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_answerodev',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen_odev', to=settings.AUTH_USER_MODEL),
        ),
    ]
