# Generated by Django 4.2.7 on 2024-08-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hafizbilgileri_adresil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='yas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
