# Generated by Django 4.2.7 on 2024-08-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_designation_organizationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='Designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.designation'),
        ),
    ]
