# Generated by Django 4.2.7 on 2025-08-10 19:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_question_answer_messagederssonuraporu_koordinator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderitem',
            options={'ordering': ['-date'], 'verbose_name': 'Talep İstek Seçenek', 'verbose_name_plural': 'Talep İstek Seçenekleri'},
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='initial_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='saved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='tax_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
