# Generated by Django 4.2.7 on 2024-07-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_course_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name': 'Talep Seçenek', 'verbose_name_plural': 'Talep Seçenekleri'},
        ),
        migrations.AlterModelOptions(
            name='completedlesson',
            options={'verbose_name': 'Tamamlanmış Ders', 'verbose_name_plural': 'Tamamlanmış Dersler'},
        ),
        migrations.AlterModelOptions(
            name='enrolledcourse',
            options={'verbose_name': 'Kaydedilan Kurs', 'verbose_name_plural': 'Kaydedilen Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='question_answer',
            options={'verbose_name': 'Soru Cevap', 'verbose_name_plural': 'Soru Cevaplar'},
        ),
        migrations.AlterModelOptions(
            name='question_answer_message',
            options={'verbose_name': 'Soru Cevap Mesaj', 'verbose_name_plural': 'Soru Cevap Mesajlar'},
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='stripe_session_id',
        ),
    ]
