# Generated by Django 4.2.7 on 2024-08-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_organizationmember_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Görev Rengi',
                'verbose_name_plural': 'Görev Renkleri',
            },
        ),
    ]
