# Generated by Django 4.2.7 on 2025-06-12 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_teacherrole_teacher_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(unique=True)),
                ('image', models.ImageField(upload_to='quran_pages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='hafiz',
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='shape_type',
            field=models.CharField(choices=[('line', 'Line'), ('circle', 'Circle')], max_length=10),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PeerID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='annotation',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quranpage'),
        ),
    ]
