# Generated by Django 4.2.7 on 2024-08-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ratingcolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingColor',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='RatingColor',
        ),
    ]
