# Generated by Django 4.2.7 on 2025-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cartorderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Baslangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100),
        ),
        migrations.AlterField(
            model_name='derssonuraporu',
            name='level',
            field=models.CharField(choices=[('Baslangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100),
        ),
        migrations.AlterField(
            model_name='eskepproje',
            name='level',
            field=models.CharField(choices=[('Baslangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100),
        ),
        migrations.AlterField(
            model_name='kitaptahlili',
            name='level',
            field=models.CharField(choices=[('Baslangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100),
        ),
        migrations.AlterField(
            model_name='odev',
            name='level',
            field=models.CharField(choices=[('Baslangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100),
        ),
    ]
