# Generated by Django 4.2.7 on 2025-06-12 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_quranpage_remove_annotation_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hatanotu',
            old_name='aciklama',
            new_name='text',
        ),
        migrations.AddField(
            model_name='hatanotu',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hatanotu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hatanotu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hatanotu',
            name='hata_turu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hatanotu',
            name='shape_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
