# Generated by Django 4.2.7 on 2024-08-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_ratingcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='baglibirim',
            field=models.IntegerField(default=0),
        ),
    ]
