# Generated by Django 4.2.7 on 2025-06-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_aciklama_hatanotu_text_hatanotu_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatanotu',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
