# Generated by Django 4.2.7 on 2025-06-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_hatanotu_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OgrenciRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AkademiStudent', 'AkademiStudent'), ('HBSStudent', 'HBSStudent'), ('HDMStudent', 'HDMStudent')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StajerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ESKEPStajer', 'ESKEPStajer')], max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Hafizbilgileri',
            new_name='Hafiz',
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='roles',
            field=models.ManyToManyField(to='api.ogrencirole', verbose_name='Roller'),
        ),
        migrations.AddField(
            model_name='stajer',
            name='roles',
            field=models.ManyToManyField(to='api.stajerrole', verbose_name='Roller'),
        ),
    ]
