# Generated by Django 4.2.7 on 2024-08-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_designation_baglibirim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='baglibirim',
            new_name='altBirim',
        ),
        migrations.AddField(
            model_name='designation',
            name='ustBirim',
            field=models.IntegerField(default=0),
        ),
    ]
