# Generated by Django 4.2.7 on 2025-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ogrencirole_stajerrole_rename_hafizbilgileri_hafiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HafizRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HBSHafiz', 'HBSHafiz'), ('HDMHafiz', 'HDMHafiz')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hafiz',
            name='roles',
            field=models.ManyToManyField(to='api.hafizrole', verbose_name='Roller'),
        ),
    ]
