# Generated by Django 4.2.7 on 2025-08-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_educatorvideolink_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatorVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='akademi-video-file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(help_text='Videoyu yükleyen eğitmen (Teacher).', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to='api.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
