# Generated by Django 4.2.7 on 2024-08-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_baglibirim_designation_altbirim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='altBirim',
        ),
    ]
