# Generated by Django 4.2.7 on 2024-08-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_designation_altbirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='birimNumarasi',
            field=models.IntegerField(default=0),
        ),
    ]
