# Generated by Django 4.2.7 on 2025-06-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hafizrole_hafiz_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HBSAgent', 'HBSAgent')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hdmhafiz',
            name='egitmen',
        ),
        migrations.RemoveField(
            model_name='hdmhafiz',
            name='user',
        ),
        migrations.AddField(
            model_name='hafiz',
            name='hdm_egitmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hafiz_ogrencileri', to='api.teacher', verbose_name='HDM Eğitmeni'),
        ),
        migrations.AlterField(
            model_name='ders',
            name='Instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='ders',
            name='hafiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hafiz'),
        ),
        migrations.AlterField(
            model_name='dersatamasi',
            name='hafiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='api.hafiz'),
        ),
        migrations.AlterField(
            model_name='dersatamasi',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='hatanotu',
            name='hafiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatalar', to='api.hafiz'),
        ),
        migrations.DeleteModel(
            name='HDMEgitmen',
        ),
        migrations.DeleteModel(
            name='HDMHafiz',
        ),
        migrations.AddField(
            model_name='agent',
            name='roles',
            field=models.ManyToManyField(to='api.agentrole', verbose_name='Roller'),
        ),
    ]
