# Generated by Django 4.2.7 on 2025-09-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_educatorvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notekitaptahlili',
            name='kitaptahlili',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.kitaptahlili'),
        ),
    ]
