# Generated by Django 4.2.7 on 2025-09-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_notekitaptahlili_kitaptahlili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answerkitaptahlili',
            name='kitaptahlili',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='api.kitaptahlili'),
        ),
    ]
