# Generated by Django 4.2.7 on 2024-08-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_designation_birimnumarasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='ReportingPerson',
        ),
    ]
