# Generated by Django 4.2.7 on 2025-06-15 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_agentrole_name_alter_ogrencirole_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dersatamasi',
            name='baslangic',
        ),
        migrations.RemoveField(
            model_name='dersatamasi',
            name='bitis',
        ),
        migrations.AddField(
            model_name='dersatamasi',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dersatamasi',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
