# Generated by Django 4.2.7 on 2025-09-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_alter_question_answerkitaptahlili_kitaptahlili'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_answer_messagekitaptahlili',
            options={'ordering': ['date'], 'verbose_name': 'Kitap Tahlili Mesajı', 'verbose_name_plural': 'Kitap Tahlili Mesajları'},
        ),
        migrations.AlterModelOptions(
            name='question_answerkitaptahlili',
            options={'ordering': ['-date'], 'verbose_name': 'Kitap Tahlili Soru Cevap', 'verbose_name_plural': 'Kitap Tahlili Soru Cevaplar'},
        ),
        migrations.RemoveField(
            model_name='question_answer_messagekitaptahlili',
            name='qa_id',
        ),
        migrations.AlterField(
            model_name='question_answer_messagekitaptahlili',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Soru Sorulan Tarih'),
        ),
        migrations.AlterField(
            model_name='question_answer_messagekitaptahlili',
            name='kitaptahlili',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_messages', to='api.kitaptahlili', verbose_name='Kitap Tahlili'),
        ),
        migrations.AlterField(
            model_name='question_answer_messagekitaptahlili',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_msg_alan_kitap', to=settings.AUTH_USER_MODEL, verbose_name='Mesajı Alan'),
        ),
        migrations.AlterField(
            model_name='question_answer_messagekitaptahlili',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_msg_gonderen_kitap', to=settings.AUTH_USER_MODEL, verbose_name='Mesajı Gönderen'),
        ),
        migrations.AlterField(
            model_name='question_answer_messagekitaptahlili',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='question_answer_messagekitaptahlili',
            name='qam_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True, verbose_name='Soru Cevap Numarası'),
        ),
        migrations.AlterField(
            model_name='question_answer_messagekitaptahlili',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.question_answerkitaptahlili', verbose_name='Soru Başlığı'),
        ),
    ]
