# Generated by Django 4.2.7 on 2024-09-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_organizationmember_reportingperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
