# Generated by Django 4.2.7 on 2025-09-01 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.files
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_question_answer_messagekitaptahlili_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='PDF, Word, PowerPoint vb. (maks. 50 MB).', upload_to=utils.files.educator_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'rtf', 'odt', 'csv', 'md']), utils.files.validate_file_size])),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False, help_text='Bayt cinsinden.')),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('is_public', models.BooleanField(default=False, help_text='Herkese açık mı?')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayırın. Örn: pdf, sunum', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(help_text='Dökümanı yükleyen eğitmen (Teacher).', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='api.teacher')),
            ],
            options={
                'verbose_name': 'Eğitmen Dökümanı',
                'verbose_name_plural': 'Eğitmen Dökümanları',
                'ordering': ['-created_at'],
            },
        ),
    ]
