# Generated by Django 4.2.7 on 2025-06-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_dersatamasi_baslangic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
