# Generated by Django 4.2.7 on 2024-10-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_organizationmember_email_organizationmember_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proje Ado',
                'verbose_name_plural': 'Projeler',
            },
        ),
    ]
