# Generated by Django 4.2.7 on 2024-10-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_proje'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='image',
            field=models.FileField(blank=True, default='category.jpg', null=True, upload_to='proje-file'),
        ),
    ]
