# Generated by Django 4.2.7 on 2025-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ders_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersatamasi',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dersatamasi',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
