# Generated by Django 4.2.7 on 2024-10-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_proje_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='image',
            field=models.FileField(blank=True, default='HBS.png', null=True, upload_to='proje-file'),
        ),
    ]
