# Generated by Django 4.2.7 on 2025-09-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_videopurchase_videoenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_answer_messageodev',
            options={'ordering': ['created_at'], 'verbose_name': 'Ödev Soru Cevap Mesaj', 'verbose_name_plural': 'Ödev Soru Cevap Mesajlar'},
        ),
        migrations.RenameField(
            model_name='question_answer_messageodev',
            old_name='date',
            new_name='created_at',
        ),
    ]
