# Generated by Django 4.2.7 on 2025-06-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_dersatamasi_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ders',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ders',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dersatamasi',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dersatamasi',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
