# Generated by Django 4.2.7 on 2024-10-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_proje_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafizbilgileri',
            name='onaydurumu',
            field=models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaylanmadı', 'Onaylanmadı')], default='Onaylanmadı', max_length=150),
        ),
    ]
