# Generated by Django 4.2.7 on 2025-06-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_ders_end_time_alter_ders_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='roles',
            field=models.ManyToManyField(default='HBSTemsilci', to='api.agentrole', verbose_name='Roller'),
        ),
    ]
