# Generated by Django 4.2.7 on 2025-07-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_agent_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hafiz',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hafizlar', to='api.agent'),
        ),
        migrations.AlterField(
            model_name='koordinatorrole',
            name='name',
            field=models.CharField(choices=[('ESKEPOgrenciKoordinator', 'ESKEPOgrenciKoordinator'), ('ESKEPStajerKoordinator', 'ESKEPStajerKoordinator'), ('ESKEPGenelKoordinator', 'ESKEPGenelKoordinator'), ('AkademiKoordinator', 'AkademiKoordinator'), ('HBSKoordinator', 'HBSKoordinator'), ('HDMKoordinator', 'HDMKoordinator')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ogrencirole',
            name='name',
            field=models.CharField(choices=[('AkademiOgrenci', 'AkademiOgrenci'), ('HBSOgrenci', 'HBSOgrenci'), ('HDMOgrenci', 'HDMOgrenci'), ('ESKEPOgrenci', 'ESKEPOgrenci')], max_length=50, unique=True),
        ),
    ]
