# Generated by Django 4.2.7 on 2024-10-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_hafizbilgileri_onaydurumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='gender',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='', max_length=50),
        ),
    ]
