# Generated by Django 4.2.7 on 2025-07-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_district_name_alter_hafiz_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('jitsi', 'Jitsi Meet')], max_length=50)),
                ('platform_url', models.URLField()),
            ],
        ),
    ]
