# Generated by Django 4.2.7 on 2025-09-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_aboutcard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('year', models.CharField(max_length=12, verbose_name='Yıl/Yıl aralığı')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('text', models.TextField(blank=True, verbose_name='Metin')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.aboutpage', verbose_name='Sayfa')),
            ],
            options={
                'verbose_name': 'Dönüm noktası',
                'verbose_name_plural': 'Dönüm noktaları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
