# Generated by Django 4.2.7 on 2025-07-29 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_livelesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odev',
            name='hazirlayan',
        ),
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='inserteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odev',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='odev',
            name='inserteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variantodev',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantodev',
            name='inserteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
