# Generated by Django 4.2.7 on 2025-03-03 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ogrenci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('image', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Turkce', 'Türkçe'), ('Ingilizce', 'İngilizce'), ('Arapca', 'Arapça')], default='Turkce', max_length=100)),
                ('level', models.CharField(choices=[('Başlangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100)),
                ('platform_status', models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayinlanmis', max_length=100)),
                ('teacher_course_status', models.CharField(choices=[('Taslak', 'Taslak'), ('Pasif', 'Pasif'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayinlanmis', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('course_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'verbose_name': 'Ödev',
                'verbose_name_plural': 'Ödevler',
            },
        ),
    ]
