# Generated by Django 4.2.7 on 2025-10-31 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_aboutmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EskepPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='eskephakkimizda', unique=True)),
                ('intro_chip', models.CharField(blank=True, default='Modül • ESKEP', max_length=120)),
                ('title', models.CharField(default='ESKEP Hakkında', max_length=200)),
                ('subtitle', models.TextField(blank=True, default='Öğrenci/stajyer ders sonu raporları, ödev, proje ve kitap tahlillerinin yüklendiği ve izlendiği modül.')),
                ('hero_image', models.URLField(blank=True, default='https://www.ehad.org.tr/wp-content/uploads/2015/07/EHAD-GENEL-MERKEZ-2018-YONETIM-KURULU-DIB-ALI-ERBAS-ZIYARETI-1600-810001-370x250.jpg')),
                ('shot1', models.URLField(blank=True, default='https://www.ehad.org.tr/wp-content/uploads/2015/07/SLIDER-DISARI-EHAD-GENEL-MERKEZ-2018-YONETIM-KURULU-DIB-ALI-ERBAS-ZIYARETI-1600-810001-370x250.jpg')),
                ('shot2', models.URLField(blank=True, default='https://www.ehad.org.tr/wp-content/uploads/2018/02/EHAD-GENEL-MERKEZ-2018-YONETIM-KURULU-DIB-ALI-ERBAS-ZIYARETI-001-370x250.jpg')),
                ('logo', models.URLField(blank=True, default='https://www.ehad.org.tr/wp-content/uploads/2025/08/istanbul-medeniyet-universitesi-protokolu-2025-150x150.jpeg')),
                ('css', models.TextField(blank=True, help_text='React tarafına direkt vereceğin custom CSS buraya yazılabilir.')),
            ],
            options={
                'verbose_name': 'ESKEP Sayfası',
                'verbose_name_plural': 'ESKEP Sayfası',
            },
        ),
        migrations.CreateModel(
            name='EskepStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.eskeppage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EskepGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.eskeppage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EskepCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lead', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True, help_text='Her satır bir madde olacak şekilde yaz.')),
                ('pills', models.CharField(blank=True, help_text='Örn: Öğrenci,Danışman,Koordinatör,Yönetici', max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.eskeppage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
