# Generated by Django 4.2.7 on 2025-03-03 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_odev'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOdev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('variant_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Odev Müfredat',
                'verbose_name_plural': 'Odev Müfredat Bölümleri',
            },
        ),
        migrations.RenameField(
            model_name='odev',
            old_name='teacher_course_status',
            new_name='teacher_odev_status',
        ),
        migrations.RemoveField(
            model_name='odev',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='odev',
            name='slug',
        ),
        migrations.CreateModel(
            name='VariantOdevItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('content_duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview', models.BooleanField(default=False)),
                ('variant_item_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantOdev_items', to='api.variantodev')),
            ],
            options={
                'verbose_name': 'Ödev Bölüm',
                'verbose_name_plural': 'Ödev Bölümler',
            },
        ),
        migrations.AddField(
            model_name='variantodev',
            name='odev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.odev'),
        ),
    ]
