# Generated by Django 4.2.7 on 2025-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_eskeppage_eskepstat_eskepgalleryitem_eskepcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(choices=[('Genel', 'Genel'), ('Eğitim / Kurs', 'Eğitim / Kurs'), ('Gönüllülük', 'Gönüllülük'), ('Bağış', 'Bağış'), ('İş Birliği', 'İş Birliği'), ('Diğer', 'Diğer')], default='Genel', max_length=50)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
