# Generated by Django 4.2.7 on 2025-03-03 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_variantodev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odev',
            name='stajer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stajer'),
        ),
    ]
