# Generated by Django 4.2.7 on 2025-03-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_odev_stajer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stajer',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher'),
        ),
    ]
