# Generated by Django 4.2.7 on 2025-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_blockedip_contactsubject_contactmessage_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
