# Generated by Django 4.2.7 on 2025-03-05 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_reviewodev_question_answerodev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersSonuRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('image', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Turkce', 'Türkçe'), ('Ingilizce', 'İngilizce'), ('Arapca', 'Arapça')], default='Turkce', max_length=100)),
                ('level', models.CharField(choices=[('Başlangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100)),
                ('platform_status', models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayinlanmis', max_length=100)),
                ('teacher_derssonuraporu_status', models.CharField(choices=[('Taslak', 'Taslak'), ('Pasif', 'Pasif'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayinlanmis', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('stajer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stajer')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'verbose_name': 'Ders Sonu Raporu',
                'verbose_name_plural': 'Ders Sonu Raporuler',
            },
        ),
        migrations.CreateModel(
            name='KitapTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('image', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Turkce', 'Türkçe'), ('Ingilizce', 'İngilizce'), ('Arapca', 'Arapça')], default='Turkce', max_length=100)),
                ('level', models.CharField(choices=[('Başlangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100)),
                ('platform_status', models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayinlanmis', max_length=100)),
                ('teacher_kitaptahlili_status', models.CharField(choices=[('Taslak', 'Taslak'), ('Pasif', 'Pasif'), ('Yayinlanmis', 'Yayınlanmış')], default='Yayinlanmis', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('stajer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stajer')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'verbose_name': 'Kitap Tahlili',
                'verbose_name_plural': 'Kitap Tahlilleri',
            },
        ),
        migrations.CreateModel(
            name='VariantDersSonuRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('variant_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('derssonuraporu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.derssonuraporu')),
            ],
            options={
                'verbose_name': 'Ders Sonu Raporu Müfredat',
                'verbose_name_plural': 'Ders Sonu Raporu Müfredat Bölümleri',
            },
        ),
        migrations.CreateModel(
            name='VariantKitapTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('variant_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kitaptahlili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitaptahlili')),
            ],
            options={
                'verbose_name': 'Kitap Tahlili Müfredat',
                'verbose_name_plural': 'Kitap Tahlili Müfredat Bölümleri',
            },
        ),
        migrations.CreateModel(
            name='VariantKitapTahliliItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('content_duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview', models.BooleanField(default=False)),
                ('variant_item_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantKitapTahlili_items', to='api.variantkitaptahlili')),
            ],
            options={
                'verbose_name': 'Kitap Tahlili Bölüm',
                'verbose_name_plural': 'Kitap Tahlili Bölümler',
            },
        ),
        migrations.CreateModel(
            name='VariantDersSonuRaporuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('content_duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview', models.BooleanField(default=False)),
                ('variant_item_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantDersSonuRaporu_items', to='api.variantderssonuraporu')),
            ],
            options={
                'verbose_name': 'Ders Sonu Raporu Bölüm',
                'verbose_name_plural': 'Ders Sonu Raporu Bölümler',
            },
        ),
        migrations.CreateModel(
            name='ReviewKitapTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Yıldız'), (2, '2 Yıldız'), (3, '3 Yıldız'), (4, '4 Yıldız'), (5, '5 Yıldız')], default=None)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kitaptahlili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitaptahlili')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitap Tahlili Yorum',
                'verbose_name_plural': 'Kitap Tahlili Yorumları',
            },
        ),
        migrations.CreateModel(
            name='Question_AnswerKitapTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kitaptahlili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitaptahlili')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitap Tahlili Soru Cevap',
                'verbose_name_plural': 'Kitap Tahlili Soru Cevaplar',
            },
        ),
        migrations.CreateModel(
            name='Question_AnswerDersSonuRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('derssonuraporu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.derssonuraporu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ders Sonu Raporu Soru Cevap',
                'verbose_name_plural': 'Ders Sonu Raporu Soru Cevaplar',
            },
        ),
        migrations.CreateModel(
            name='Question_Answer_MessageKitapTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('qam_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kitaptahlili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitaptahlili')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question_answerkitaptahlili')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitap Tahlili Soru Cevap Mesaj',
                'verbose_name_plural': 'Kitap Tahlili Soru Cevap Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='Question_Answer_MessageDersSonuRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('qam_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('derssonuraporu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.derssonuraporu')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question_answerderssonuraporu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ders Sonu Raporu Soru Cevap Mesaj',
                'verbose_name_plural': 'Ders Sonu Raporu Soru Cevap Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='NoteKitapTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.TextField()),
                ('note_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kitaptahlili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitaptahlili')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiatp Tahlili Not',
                'verbose_name_plural': 'Kiatp Tahlili Notları',
            },
        ),
        migrations.CreateModel(
            name='EnrolledKitapTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kitaptahlili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitaptahlili')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eğitmene Gönderilen Kitap Tahlili',
                'verbose_name_plural': 'Eğitmene Gönderilen Kitap Tahlilleri',
            },
        ),
        migrations.CreateModel(
            name='CompletedOdev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('odev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.odev')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variantitem')),
            ],
            options={
                'verbose_name': 'Tamamlanmış Ödev',
                'verbose_name_plural': 'Tamamlanmış Ödevler',
            },
        ),
        migrations.CreateModel(
            name='CompletedKitapTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kitaptahlili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitaptahlili')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variantitem')),
            ],
            options={
                'verbose_name': 'Tamamlanmış Kitap Tahlili',
                'verbose_name_plural': 'Tamamlanmış Ödevler',
            },
        ),
    ]
