# Generated by Django 4.2.7 on 2025-03-05 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_derssonuraporu_kitaptahlili_variantderssonuraporu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notekitaptahlili',
            options={'verbose_name': 'Kitap Tahlili Not', 'verbose_name_plural': 'Kitap Tahlili Notları'},
        ),
        migrations.CreateModel(
            name='WishlistOdev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('odev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.odev')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödev İstek',
                'verbose_name_plural': 'Ödev İstekler',
            },
        ),
        migrations.CreateModel(
            name='ReviewDersSonuRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Yıldız'), (2, '2 Yıldız'), (3, '3 Yıldız'), (4, '4 Yıldız'), (5, '5 Yıldız')], default=None)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('derssonuraporu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.derssonuraporu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ders Sonu Raporu Yorum',
                'verbose_name_plural': 'Ders Sonu Raporu Yorumları',
            },
        ),
        migrations.CreateModel(
            name='NoteDersSonuRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.TextField()),
                ('note_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('derssonuraporu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.derssonuraporu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ders Sonu Raporu Not',
                'verbose_name_plural': 'Ders Sonu Raporu Notları',
            },
        ),
        migrations.CreateModel(
            name='EnrolledDersSonuRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('derssonuraporu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.derssonuraporu')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eğitmene Gönderilen Ders Sonu Raporu',
                'verbose_name_plural': 'Eğitmene Gönderilen Ders Sonu Raporları',
            },
        ),
    ]
