# Generated by Django 4.2.7 on 2025-03-11 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_alter_notekitaptahlili_options_wishlistodev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derssonuraporu',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='derssonuraporu',
            name='platform_status',
        ),
        migrations.RemoveField(
            model_name='derssonuraporu',
            name='stajer',
        ),
        migrations.RemoveField(
            model_name='derssonuraporu',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='derssonuraporu',
            name='teacher_derssonuraporu_status',
        ),
        migrations.RemoveField(
            model_name='kitaptahlili',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='kitaptahlili',
            name='platform_status',
        ),
        migrations.RemoveField(
            model_name='kitaptahlili',
            name='stajer',
        ),
        migrations.RemoveField(
            model_name='kitaptahlili',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='kitaptahlili',
            name='teacher_kitaptahlili_status',
        ),
        migrations.RemoveField(
            model_name='odev',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='odev',
            name='platform_status',
        ),
        migrations.RemoveField(
            model_name='odev',
            name='stajer',
        ),
        migrations.RemoveField(
            model_name='odev',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='odev',
            name='teacher_odev_status',
        ),
        migrations.AddField(
            model_name='derssonuraporu',
            name='derssonuraporu_status',
            field=models.CharField(choices=[('Taslak', 'Taslak'), ('Teslim Edildi', 'Teslim Edildi')], default='Taslak', max_length=100),
        ),
        migrations.AddField(
            model_name='derssonuraporu',
            name='hazirlayan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='derssonuraporu',
            name='koordinator_derssonuraporu_status',
            field=models.CharField(blank=True, choices=[('Incelemede', 'Incelemede'), ('Geri Gönderildi', 'Geri Gönderildi'), ('Not Verildi', 'Not Verildi')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitaptahlili',
            name='hazirlayan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kitaptahlili',
            name='kitaptahlili_status',
            field=models.CharField(choices=[('Taslak', 'Taslak'), ('Teslim Edildi', 'Teslim Edildi')], default='Taslak', max_length=100),
        ),
        migrations.AddField(
            model_name='kitaptahlili',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='kitaptahlili',
            name='koordinator_kitaptahlili_status',
            field=models.CharField(blank=True, choices=[('Incelemede', 'Incelemede'), ('Geri Gönderildi', 'Geri Gönderildi'), ('Not Verildi', 'Not Verildi')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='odev',
            name='hazirlayan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odev',
            name='koordinator_odev_status',
            field=models.CharField(blank=True, choices=[('Incelemede', 'Incelemede'), ('Geri Gönderildi', 'Geri Gönderildi'), ('Not Verildi', 'Not Verildi')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='odev',
            name='odev_status',
            field=models.CharField(choices=[('Taslak', 'Taslak'), ('Teslim Edildi', 'Teslim Edildi')], default='Taslak', max_length=100),
        ),
        migrations.CreateModel(
            name='Koordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='course-file')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Ogrenci', 'Ogrenci'), ('Stajer', 'Stajer'), ('Genel', 'Genel')], max_length=100)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koordinator',
                'verbose_name_plural': 'Koordinatorler',
            },
        ),
        migrations.AddField(
            model_name='derssonuraporu',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='odev',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
    ]
