# Generated by Django 4.2.7 on 2025-03-11 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_remove_derssonuraporu_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EskepProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('image', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Turkce', 'Türkçe'), ('Ingilizce', 'İngilizce'), ('Arapca', 'Arapça')], default='Turkce', max_length=100)),
                ('level', models.CharField(choices=[('Başlangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri Seviye', 'İleri Seviye')], default='Baslangic', max_length=100)),
                ('eskepProje_status', models.CharField(choices=[('Taslak', 'Taslak'), ('Teslim Edildi', 'Teslim Edildi')], default='Taslak', max_length=100)),
                ('koordinator_eskepProje_status', models.CharField(blank=True, choices=[('Incelemede', 'Incelemede'), ('Geri Gönderildi', 'Geri Gönderildi'), ('Not Verildi', 'Not Verildi')], max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('hazirlayan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator')),
            ],
            options={
                'verbose_name': 'Eskep Proje',
                'verbose_name_plural': 'Eskep Projeleri',
            },
        ),
        migrations.CreateModel(
            name='VariantEskepProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('variant_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('eskepProje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eskepproje')),
            ],
            options={
                'verbose_name': 'Eskep Proje Müfredat',
                'verbose_name_plural': 'Eskep Proje Müfredat Bölümleri',
            },
        ),
        migrations.AlterModelOptions(
            name='proje',
            options={'verbose_name': 'Proje Adı', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.CreateModel(
            name='VariantEskepProjeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course-file')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('content_duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview', models.BooleanField(default=False)),
                ('variant_item_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantEskepProje_items', to='api.varianteskepproje')),
            ],
            options={
                'verbose_name': 'Eskep Proje Bölüm',
                'verbose_name_plural': 'Eskep Proje Bölümler',
            },
        ),
    ]
