# Generated by Django 4.2.7 on 2025-03-13 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_eskepproje_varianteskepproje_alter_proje_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewderssonuraporu',
            options={'verbose_name': 'Ders Sonu Raporu Notu', 'verbose_name_plural': 'Ders Sonu Raporu Notları'},
        ),
        migrations.AlterModelOptions(
            name='reviewkitaptahlili',
            options={'verbose_name': 'Kitap Tahlili Notu', 'verbose_name_plural': 'Kitap Tahlili Notları'},
        ),
        migrations.AlterModelOptions(
            name='reviewodev',
            options={'verbose_name': 'Ödev Notu', 'verbose_name_plural': 'Ödev Notları'},
        ),
        migrations.RenameField(
            model_name='enrolledderssonuraporu',
            old_name='teacher',
            new_name='egitmen',
        ),
        migrations.RenameField(
            model_name='enrolledderssonuraporu',
            old_name='user',
            new_name='hazirlayan',
        ),
        migrations.RenameField(
            model_name='enrolledkitaptahlili',
            old_name='teacher',
            new_name='egitmen',
        ),
        migrations.RenameField(
            model_name='enrolledkitaptahlili',
            old_name='user',
            new_name='hazirlayan',
        ),
        migrations.RenameField(
            model_name='enrolledodev',
            old_name='teacher',
            new_name='egitmen',
        ),
        migrations.RenameField(
            model_name='enrolledodev',
            old_name='user',
            new_name='hazirlayan',
        ),
        migrations.RenameField(
            model_name='notederssonuraporu',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='notekitaptahlili',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='noteodev',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='question_answer_messagederssonuraporu',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='question_answer_messagekitaptahlili',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='question_answer_messageodev',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='question_answerderssonuraporu',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='question_answerkitaptahlili',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='question_answerodev',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='reviewderssonuraporu',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='reviewkitaptahlili',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.RenameField(
            model_name='reviewodev',
            old_name='user',
            new_name='ogrenciStajer',
        ),
        migrations.AddField(
            model_name='enrolledderssonuraporu',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='enrolledkitaptahlili',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='enrolledodev',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='notederssonuraporu',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='notekitaptahlili',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='noteodev',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='question_answer_messagederssonuraporu',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='question_answer_messagekitaptahlili',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='question_answer_messageodev',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='question_answerderssonuraporu',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='question_answerkitaptahlili',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='question_answerodev',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='reviewderssonuraporu',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='reviewkitaptahlili',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AddField(
            model_name='reviewodev',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.AlterField(
            model_name='stajer',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
        migrations.CreateModel(
            name='ReviewEskepProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Yıldız'), (2, '2 Yıldız'), (3, '3 Yıldız'), (4, '4 Yıldız'), (5, '5 Yıldız')], default=None)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('eskepproje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eskepproje')),
                ('koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator')),
                ('ogrenciStajer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eskep Proje Notu',
                'verbose_name_plural': 'Eskep Proje Notları',
            },
        ),
        migrations.CreateModel(
            name='Question_AnswerEskepProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('eskepproje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eskepproje')),
                ('koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator')),
                ('ogrenciStajer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eskep Proje Soru Cevap',
                'verbose_name_plural': 'Eskep Proje Soru Cevaplar',
            },
        ),
        migrations.CreateModel(
            name='Question_Answer_MessageEskepProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('qam_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('eskepproje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eskepproje')),
                ('koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator')),
                ('ogrenciStajer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question_answerderssonuraporu')),
            ],
            options={
                'verbose_name': 'Eskep Proje Soru Cevap Mesaj',
                'verbose_name_plural': 'Eskep Proje Soru Cevap Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='NoteEskepProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.TextField()),
                ('note_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('eskepproje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.derssonuraporu')),
                ('koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator')),
                ('ogrenciStajer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eskep Proje Not',
                'verbose_name_plural': 'Eskep Proje Notları',
            },
        ),
        migrations.CreateModel(
            name='EnrolledEskepProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('egitmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher')),
                ('eskepproje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eskepproje')),
                ('hazirlayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator')),
            ],
            options={
                'verbose_name': 'Koordinatore Gönderilen Proje',
                'verbose_name_plural': 'Koordinatore Gönderilen Projeler',
            },
        ),
    ]
