# Generated by Django 4.2.7 on 2025-03-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_reviewderssonuraporu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='koordinator',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='derssonuraporu',
            name='derssonuraporu_status',
            field=models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Teslim Edildi', 'Teslim Edildi')], default='Taslak', max_length=100),
        ),
        migrations.AlterField(
            model_name='eskepproje',
            name='eskepProje_status',
            field=models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Teslim Edildi', 'Teslim Edildi')], default='Taslak', max_length=100),
        ),
        migrations.AlterField(
            model_name='kitaptahlili',
            name='kitaptahlili_status',
            field=models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Teslim Edildi', 'Teslim Edildi')], default='Taslak', max_length=100),
        ),
        migrations.AlterField(
            model_name='odev',
            name='odev_status',
            field=models.CharField(choices=[('İncelemede', 'İncelemede'), ('Pasif', 'Pasif'), ('Reddedilmiş', 'Reddedilmiş'), ('Taslak', 'Taslak'), ('Teslim Edildi', 'Teslim Edildi')], default='Taslak', max_length=100),
        ),
    ]
