# Generated by Django 4.2.7 on 2025-03-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_koordinator_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stajer',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator'),
        ),
    ]
