# Generated by Django 4.2.7 on 2025-04-14 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0033_teacher_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_answer_messageodev',
            options={'ordering': ['date'], 'verbose_name': 'Ödev Soru Cevap Mesaj', 'verbose_name_plural': 'Ödev Soru Cevap Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='question_answerodev',
            options={'ordering': ['-date'], 'verbose_name': 'Ödev Soru Cevap', 'verbose_name_plural': 'Ödev Soru Cevaplar'},
        ),
        migrations.RemoveField(
            model_name='question_answer_messageodev',
            name='koordinator',
        ),
        migrations.RemoveField(
            model_name='question_answer_messageodev',
            name='ogrenciStajer',
        ),
        migrations.RemoveField(
            model_name='question_answerodev',
            name='koordinator',
        ),
        migrations.RemoveField(
            model_name='question_answerodev',
            name='ogrenciStajer',
        ),
        migrations.AddField(
            model_name='question_answer_messageodev',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiAlan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answer_messageodev',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qam_mesajiGonderen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answerodev',
            name='mesajiAlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qao_mesajiAlan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_answerodev',
            name='mesajiGonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qao_mesajiGonderen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteodev',
            name='odev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.odev'),
        ),
        migrations.AlterField(
            model_name='question_answerodev',
            name='odev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='api.odev'),
        ),
    ]
