# Generated by Django 4.2.7 on 2025-04-14 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_alter_question_answer_messageodev_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitaptahlili',
            name='hazirlayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitaptahlili',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koordinated_kitaplar', to='api.koordinator'),
        ),
        migrations.CreateModel(
            name='NoteProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.TextField()),
                ('note_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.koordinator')),
                ('ogrenciStajer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eskepproje')),
            ],
            options={
                'verbose_name': 'Proje Not',
                'verbose_name_plural': 'Proje Notları',
            },
        ),
    ]
