# Generated by Django 4.2.7 on 2025-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_kitaptahlili_hazirlayan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(choices=[('line', 'Line'), ('circle', 'Circle')], max_length=10)),
                ('coordinates', models.JSONField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
