# Generated by Django 4.2.7 on 2025-05-26 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_eskepevent_teacherstudent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherstudent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eskepevent',
            name='user',
        ),
        migrations.AddField(
            model_name='eskepevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eskepevent',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='instructor',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eskepevent',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstudent',
            unique_together={('user', 'instructor')},
        ),
        migrations.RemoveField(
            model_name='teacherstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherstudent',
            name='teacher',
        ),
    ]
