"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 4.2.
"""

from datetime import timedelta
from pathlib import Path
import os
from urllib.parse import urlparse
from environs import Env

# -------------------------------------------------
# ENV & PATHS
# -------------------------------------------------
env = Env()
env.read_env()  # .env dosyasını oku

BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
PROJECT_DIR = Path(__file__).resolve().parent

# -------------------------------------------------
# CORE / SECURITY
# -------------------------------------------------
DEBUG = env.bool("DEBUG", default=False)

# Güvenlik anahtarını .env'den zorunlu çek
SECRET_KEY = env.str("SECRET_KEY", default="!!!-SET-IN-ENV-!!!")

# Alan adlarını proje alanlarına göre sabitledik, gerekirse .env üzerinden ALLOWED_HOSTS ekleyebilirsin
ALLOWED_HOSTS = [
    "api.akademi.ehad.org.tr",
    "akademi.ehad.org.tr",
    "api.ehad.org.tr",
    "izem.ehad.org.tr",
    "185.8.129.89",
]
if DEBUG:
    ALLOWED_HOSTS += ["127.0.0.1", "localhost"]

# — CSRF Trusted Origins
def _collect_known_origins() -> list[str]:
    origins = [
        "https://api.akademi.ehad.org.tr",
        "https://akademi.ehad.org.tr",
        "https://api.ehad.org.tr",
        "https://izem.ehad.org.tr",
    ]
    # .env’deki URL’leri de ekle (varsa)
    for key in ("FRONTEND_SITE_URL", "FRONTEND_SITE_TEST_URL", "SITE_URL"):
        url = env.str(key, default="").strip()
        if not url:
            continue
        # Django, şema (http/https) zorunlu istiyor
        parsed = urlparse(url)
        if parsed.scheme and parsed.netloc:
            origins.append(f"{parsed.scheme}://{parsed.netloc}")
    return list(dict.fromkeys(origins))  # unique & order-preserve

CSRF_TRUSTED_ORIGINS = _collect_known_origins()

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = not DEBUG

SESSION_COOKIE_SECURE = not DEBUG or True
CSRF_COOKIE_SECURE = not DEBUG or True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

if DEBUG:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

# -------------------------------------------------
# APPS
# -------------------------------------------------
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django_admin_logs",
    "django_extensions",

    # Custom Apps
    "core",
    "api",
    "customer",
    "store",
    "userauths",
    "vendor",

    # Third Party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "anymail",
    "drf_yasg",
    
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            PROJECT_ROOT / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# -------------------------------------------------
# DATABASE
#  - Varsayılan: SQLite (hızlı başlatma)
#  - MySQL'e geçmek istersen .env'de DB_* değerlerini doldur
# -------------------------------------------------
DB_ENGINE = env.str("DB_ENGINE", default="django.db.backends.sqlite3")
if DB_ENGINE == "django.db.backends.sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": env.str("DB_NAME", default=str(BASE_DIR / "db.sqlite3")),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,  # ör: django.db.backends.mysql
            "NAME": env.str("DB_NAME"),
            "USER": env.str("DB_USER"),
            "PASSWORD": env.str("DB_PASSWORD"),
            "HOST": env.str("DB_HOST", default="localhost"),
            "PORT": env.str("DB_PORT", default="3306"),
            "OPTIONS": {"charset": "utf8mb4"},
        }
    }

# -------------------------------------------------
# PASSWORD VALIDATORS
# -------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------
# I18N / TZ
# -------------------------------------------------
LANGUAGE_CODE = "tr"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------
# STATIC & MEDIA
# -------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -------------------------------------------------
# AUTH / EMAIL / ANYMAIL
# -------------------------------------------------
AUTH_USER_MODEL = "userauths.User"

FROM_EMAIL = env.str("FROM_EMAIL", default=None)

MAILGUN_API_KEY = env.str("MAILGUN_API_KEY", default=None)
MAILGUN_SENDER_DOMAIN = env.str("MAILGUN_SENDER_DOMAIN", default=None)

if MAILGUN_API_KEY and MAILGUN_SENDER_DOMAIN:
    ANYMAIL = {
        "MAILGUN_API_KEY": MAILGUN_API_KEY,
        "MAILGUN_SENDER_DOMAIN": MAILGUN_SENDER_DOMAIN,
    }
    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
else:
    # Mailgun yoksa console'a düş
    EMAIL_BACKEND = env.str(
        "EMAIL_BACKEND",
        default="django.core.mail.backends.console.EmailBackend",
    )

FRONTEND_SITE_URL = env.str("FRONTEND_SITE_URL", default=None)

# -------------------------------------------------
# DRF / JWT
# -------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=50),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# -------------------------------------------------
# CORS
# -------------------------------------------------
# Prod'da tüm kökenler açık olmasın
CORS_ALLOW_ALL_ORIGINS = False
# .env’deki front-end URL’lerini CORS’a da taşı
def _cors_from_env() -> list[str]:
    items = set()
    for key in ("FRONTEND_SITE_URL", "FRONTEND_SITE_TEST_URL", "SITE_URL"):
        u = env.str(key, default="").strip()
        if not u:
            continue
        parsed = urlparse(u)
        if parsed.scheme and parsed.netloc:
            items.add(f"{parsed.scheme}://{parsed.netloc}")
    # known domains (https)
    items.update({
        "https://akademi.ehad.org.tr",
        "https://api.akademi.ehad.org.tr",
        "https://izem.ehad.org.tr",
    })
    if DEBUG:
        items.update({
            "http://localhost:5173",
            "http://127.0.0.1:5173",
            "http://localhost:8000",
            "http://127.0.0.1:8000",
        })
    return sorted(items)

CORS_ALLOWED_ORIGINS = _cors_from_env()
CORS_ALLOW_CREDENTIALS = True

# -------------------------------------------------
# SWAGGER (drf_yasg)
# -------------------------------------------------
SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    "LOGIN_URL": "admin:login",
    "LOGOUT_URL": "admin:logout",
}

# -------------------------------------------------
# JAZZMIN
# -------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Hafızlık Uygulaması Admin Paneli",
    "site_header": "EHAD Admin Paneli",
    "site_brand": "Hafızlık Uygulaması",
    "site_logo": "path-to-logo",
    "welcome_sign": "Admin Paneline Hoşgeldiniz",
    "copyright": "EHAD",
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-danger",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# -------------------------------------------------
# PAYMENTS (Stripe / PayPal)
# -------------------------------------------------
STRIPE_SECRET_KEY = env.str("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = env.str("STRIPE_PUBLIC_KEY", default="")
PAYPAL_CLIENT_ID = env.str("PAYPAL_CLIENT_ID", default="")
PAYPAL_SECRET_ID = env.str("PAYPAL_SECRET_ID", default="")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
